fint:
  org-id: ${fint.org-id}
  flyt:
    resource-gateway:
      authorization:
        enable: true
  client:
    base-url: https://beta.felleskomponent.no
  kafka:
    default-replicas: 1
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    hikari:
      schema: fylke_no
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fint-kontroll-role-catalog
    username: role_catalog
    password: 123456

