fint:
  application-id: fint-kontroll-role-catalog
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user
  kontroll:
    role-catalog:
      pagesize: 50
      publishing:
        initial-delay: 600000
        fixed-delay: 900000
      persisting:
        initial-delay: 180000
        fixed-delay: 900000
    opa:
      url: http://fint-kontroll-opa:8181/v1/data/accessmanagement
    authorization:
      authorized-role: 'https://role-catalog.vigoiks.no/vigo/kontroll/user'
      authorized-admin-role: 'https://role-catalog.vigoiks.no/vigo/kontroll/admin'
      authorized-org-id: 'vigo.no'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  profiles:
    include:
      - kafka
      - db
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    no.fintlabs.cache.ehcache: WARN

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

  envFrom:
    - configMapRef:
        name: fint-environment
    - configMapRef:
        name: fint-kontroll-rolecatalog-config
