fint:
  org-id: fintlabs.no
  flyt:
    resource-gateway:
      authorization:
        enable: true
  client:
    base-url: https://beta.felleskomponent.no
  kafka:
    default-replicas: 1
  kontroll:
    opa:
      url: http://localhost:8181/v1/data/accessmanagement
    role-catalog:
      pagesize: 50
#      publishing:
#        initial-delay: 30000
#        fixed-delay: 60000
      persisting:
        initial-delay: 10000
        fixed-delay: 60000
spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      schema: roles
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id: ${fint.client-id}
            client-secret: ${fint.client-secret}
            provider: fint-idp
            scope: fint-client
server:
  port: 8090
logging:
  level:
    root: INFO
    #org.apache.kafka: INFO