fint:
  application-id: fint-kontroll-role-catalog
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user
  kontroll:
    role-catalog:
      pagesize: 50
    opa:
      url: http://fint-kontroll-opa:8181/v1/data/accessmanagement
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  profiles:
    include:
      - kafka
      - db
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
springdoc:
  swagger-ui:
    path: /api/swagger/
    enabled: true
  api-docs:
    path: /api/api-docs/
