apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-role-catalog
  app.kubernetes.io/instance: fint-kontroll-role-catalog_afk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: afk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "afk-no.kontroll.*"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/afk-no/api/roles"
      - op: replace
        path: "/spec/url/basePath"
        value: "/afk-no"
      - op: replace
        path: "/spec/env/0/value"
        value: "afk.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "afk-no-fint-kontroll-role-catalog"
      - op: replace
        path: "/spec/env/2/value"
        value: "-XX:+ExitOnOutOfMemoryError -Xms512m -Xmx1408m -verbose:gc"
      - op: replace
        path: "/spec/resources"
        value: 
          limits:
            cpu: "2000m"
            memory: "1512Mi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"

    target:
      kind: Application
      name: fint-kontroll-role-catalog
