apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-role-catalog
  app.kubernetes.io/instance: fint-kontroll-role-catalog_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/fintlabs-no/api/roles"
      - op: replace
        path: "/spec/url/basePath"
        value: "/fintlabs-no"
      - op: replace
        path: "/spec/env/0/value"
        value: "vigo.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "fintlabs-no-fint-kontroll-role-catalog"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/fintlabs-no/actuator/prometheus"
      - op: replace
        path: "/spec/env/2/value"
        value: "-XX:+ExitOnOutOfMemoryError -Xmx1950m"
      - op: replace
        path: "/spec/resources"
        value:
          limits:
            cpu: "2000m"
            memory: "2000Mi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"
      - op: replace
        path: "/spec/url/hostname"
        value: "kontroll.novari.no"
    target:
      kind: Application
      name: fint-kontroll-role-catalog
