apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-role-catalog
  app.kubernetes.io/instance: fint-kontroll-role-catalog_vlfk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: vlfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "vlfk.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vlfk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "vlfk-no.kontroll.*"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/vlfk-no/api/roles"
      - op: replace
        path: "/spec/url/hostname"
        value: "kontroll.novari.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/vlfk-no"
      - op: replace
        path: "/spec/env/0/value"
        value: "vlfk.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "vlfk-no-fint-kontroll-role-catalog"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/vlfk-no/actuator/prometheus"
      - op: replace
        path: "/spec/env/2/value"
        value: "-XX:+ExitOnOutOfMemoryError -Xmx1950m"
      - op: replace
        path: "/spec/resources"
        value:
          limits:
            cpu: "2000m"
            memory: "2000Mi"
          requests:
            cpu: "1000m"
            memory: "1024Mi"

    target:
      kind: Application
      name: fint-kontroll-role-catalog
