apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-role-catalog
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-role-catalog:latest
  imagePullPolicy: Always
  url:
    hostname: kontroll.vigoiks.no
    basePath: /beta/fintlabs-no
  ingress:
    enabled: true
    basePath: /beta/fintlabs-no/api/roles
    middlewares:
      - fint-kontroll-sso
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
  database:
    database: fint-kontroll
  env:
    - name: fint.kontroll.authorization.authorized-org-id
      value: 'vigo.no'
    - name: spring.kafka.consumer.group-id
      value: 'fint-kontroll-role-catalog'
    - name: JAVA_TOOL_OPTIONS
      value: "-XX:+ExitOnOutOfMemoryError -Xms768m -Xmx768m -verbose:gc"
  envFrom:
    - configMapRef:
        name: fint-environment
    - configMapRef:
        name: fint-kontroll-rolecatalog-config
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 1024Mi
      cpu: 1000m
